#!/usr/bin/env python3
"""
Registers one Sentinel app per flight-recorder tenant, so generated traces
have somewhere real to land. Run this once before using `--sink sentinel`.

    python3 register_with_sentinel.py
    python3 register_with_sentinel.py --sentinel-url http://localhost:4000

Writes sentinel-config.json:

    {
      "northwind": {"appId": "...", "ingestKey": "...", "sentinelTenantId": "t-northwind"},
      "acmehealth": {...},
      "zephyr": {...}
    }

harness/sinks.py's SentinelSink reads this file to know which app/ingest-key
to POST each flight-recorder tenant's traces under. Declared PII is
deliberately narrower than what the generator's pii_leak scenario actually
plants (see RUN.md's stub-collector findings table: CREDIT_CARD, EMAIL, DOB,
PHONE, PASSPORT, SIN_CA, IPV4) — see AGENT_MANDATE.md at the repo root for
why that gap is the point, not a bug.
"""
from __future__ import annotations

import argparse
import json
import sys
import urllib.error
import urllib.request

# flight-recorder tenant_id -> the Sentinel app-owner account that should own
# its RAG app, and the Sentinel tenant that account belongs to.
TENANT_MAP = {
    "northwind": {
        "sentinelTenantId": "t-northwind",
        "ownerEmail": "jae.kim@northwind.com",
        "ownerPassword": "password123",
        "region": "US",
    },
    "acmehealth": {
        "sentinelTenantId": "t-acme",
        "ownerEmail": "dr.chen@acmehealth.eu",
        "ownerPassword": "password123",
        "region": "EU",
    },
    "zephyr": {
        "sentinelTenantId": "t-zephyr",
        "ownerEmail": "sam.okafor@zephyrfinancial.com",
        "ownerPassword": "password123",
        "region": "US",
    },
}

APP_NAME = "RAG Support Agent (flight-recorder)"
DECLARED_PII = ["EMAIL", "CREDIT_CARD"]  # narrower than what pii_leak actually plants, on purpose
RETENTION_DAYS = 90


def post_json(url: str, body: dict, token: str | None = None) -> dict:
    data = json.dumps(body).encode()
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    req = urllib.request.Request(url, data=data, headers=headers, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=10) as r:
            return json.loads(r.read())
    except urllib.error.HTTPError as e:
        detail = e.read().decode(errors="replace")
        raise SystemExit(f"POST {url} -> {e.code}: {detail}")


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--sentinel-url", default="http://localhost:4000")
    p.add_argument("--config", default="sentinel-config.json")
    p.add_argument("--force", action="store_true", help="re-register even if config exists")
    args = p.parse_args()

    try:
        with open(args.config) as f:
            existing = json.load(f)
    except FileNotFoundError:
        existing = {}

    if existing and not args.force:
        print(f"{args.config} already has {len(existing)} tenant(s) registered. "
              f"Use --force to re-register.", file=sys.stderr)
        return

    config = {}
    for fr_tenant, cfg in TENANT_MAP.items():
        print(f"Registering flight-recorder tenant {fr_tenant!r} against Sentinel "
              f"({cfg['sentinelTenantId']}) ...")
        login = post_json(f"{args.sentinel_url}/api/auth/login",
                           {"email": cfg["ownerEmail"], "password": cfg["ownerPassword"]})
        token = login["token"]

        app = post_json(f"{args.sentinel_url}/api/apps", {
            "name": APP_NAME,
            "region": cfg["region"],
            "retention_days": RETENTION_DAYS,
            "deletion_allowed": True,
            "declared_pii": DECLARED_PII,
            "purpose": "RAG support agent traffic generated by flight-recorder for demo/testing",
        }, token=token)

        config[fr_tenant] = {
            "appId": app["id"],
            "ingestKey": app["ingest_key"],
            "sentinelTenantId": cfg["sentinelTenantId"],
        }
        print(f"  -> appId={app['id']}  declared_pii={app['declared_pii']}")

    with open(args.config, "w") as f:
        json.dump(config, f, indent=2)
    print(f"\nWrote {args.config}. Now run traffic with --sink sentinel (or sqlite,sentinel).")


if __name__ == "__main__":
    main()
